routes/web.php
<?php

use App\Jobs\SendEmailsJob;
use App\Mail\NewUser;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Mail;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//dashboard - home.blade.php
Route::group(['middleware' => 'forceSSL'], function() {

//change language
Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
});
//user needs to be logged in routes
Route::group(['middleware' => 'auth'], function(){
    Route::get('/', 'HomeController@index')->name('home');

    //mail routes
    Route::get('/mail/{collegium_id?}', 'MailController@index');
    Route::post('/sendmail', 'MailController@sendMailToOneUser')->name('sendmail');
    //zyrtaret
    Route::get('/officials/{city}', 'OfficialController@showByCity');
    Route::get('/official/archive', 'OfficialController@archiveIndex')->name('archive');
    Route::resource('/official', 'OfficialController');
    Route::patch('/official/{id}/ndrysho', 'OfficialController@ndrysho')->name('official.ndrysho');
    Route::patch('/official/{id}/headship', 'OfficialController@addToHeadShip')->name('addToHeadShip');
    Route::patch('/official/{id}/headship/remove', 'OfficialController@removeFromHeadship')->name('removeFromHeadship');
    //kolegjiumet
    Route::resource('/collegium', 'CollegiumController');
    //komunat
    Route::get('/municipalities', 'MunicipalityController@index');
    //perdoruesit
    Route::resource('/user', 'UserController');

    //calendar
    Route::group(['prefix' => 'calendar/'], function () {
        Route::get('/', 'CalendarController@index');
        Route::post('/action', 'CalendarController@action');
    });

    //file-storage
    Route::group(['prefix' => 'file/'], function () {
        Route::get('/', 'FileController@index');
        Route::get('/create', 'FileController@create');
        Route::post('/store', 'FileController@store')->name('store.image');
        Route::get('/{id}/download', 'FileController@download')->name('download.image');
        Route::delete('/{id}/delete', 'FileController@destroy')->name('delete.image');
    });

    Route::get('/logout', 'Auth\LoginController@logout');
});
//Auth::routes(['register' => false]);

Auth::routes();

Route::get('/register', function (){
   return redirect('login');
});
});

resources/views/city.blade.php
@extends('layouts.app')

@section('page_name', __('messages.Municipalities'))

@section('content')
    <style type="text/css">
    	.butoni {
    		padding: 0;
border: none;
background: none;
outline: none;
border-color: white;
font-size: 100%;

    	}
selector:focus {outline: none;}
    </style>

<div class="container">
<div class="row">

	@foreach($cities as $city)
  <div class="col-lg-4" style="margin-bottom: 20px;">
	<a href="{{url('/officials/'.$city->name.'')}}" style="text-decoration: none; color: black;">
        <section class="card card-featured-left card-featured-primary ">
		<div class="card-body">
			<h3 class="title">{{ucfirst($city->name)}}</h3>
		</div>
	</section></a>
	</div>
  @endforeach
</div>

</div>


@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('page_name', __('messages.Dashboard'))

@section('custom_header')

@endsection

@section('content')
    <style type="text/css">
        .butoni {
            padding: 0;
            border: none;
            background: none;
            outline: none;
            border-color: white;
            font-size: 100%;
        }

        selector:focus {
            outline: none;
        }

    </style>
    <div class="row">

        @forelse($collegiums as $collegium)
            <div class="col-md-4">
                <section class="card card-featured-left card-featured-primary mb-4">
                    {{-- <a href="{{route('collegium.show', $collegium->id)}}" style="text-decoration: none; color: black;"> --}}
                    <a href="#" style="text-decoration: none; color: black;">
                        <div onclick="openmodal({{$collegium->id}})" class="card-body">
                            <div class="widget-summary widget-summary-xlg">
                                <div class="widget-summary-col widget-summary-col-icon">
                                    <div>
                                        <i class=""><img src="{{asset($collegium->image)}}" width="100" style="padding: 10px;"></i>
                                    </div>
                                </div>
                                <div class="widget-summary-col">
                                    <div>
                                        <h3 id="title{{$collegium->id}}" class="title" style="float: left;  margin-left: 3px;">{{$collegium->title}}</h3><br>
                                        <hr style="opacity: 0%;">
                                        <div class="info">
                                                               <h3 class="amount"> {{count($collegium->officials)}}</h3>
                                                        </div>
                                        <div style="float: left;">
                                            @if($collegium->description != null)
                                                <span id="description{{$collegium->id}}" style="
  display:inline-block;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  max-width: 25ch;">{{$collegium->description}}</span>
                                            @else
                                                <span id="description{{$collegium->id}}" disabled>{{__('messages.No description for this collegium')}}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </section>
            </div>
        @empty
            <div class="col-md-12">
                <div class="alert alert-danger text-center">
                    <strong>{{__('messages.Sorry, No Record to show')}}. {{__('messages.Want to add')}} <a href="{{route('collegium.create')}}">{{__('messages.some?')}}</a></strong>
                </div>
            </div>
        @endforelse
    </div>


<div class="modal fade" id="mymodal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Modal body text goes here.</p>
      </div>
      <div class="modal-footer">
        <a id="modal-link" href="#" class="btn btn-primary">{{__('messages.Seemore')}}</a>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{{__('messages.Close')}}</button>
      </div>
    </div>
  </div>
</div>
@endsection

@section('custom_footer')
<script>
    function openmodal(id){
        $("#mymodal").modal('show');
        // console.log();
        var title = $("#title"+id).html();
        var desc = $("#description"+id).html();
        var url = '/collegium/'+id;
        $(".modal-title").html(title);
        $(".modal-body").html(desc);
        $("#modal-link").attr("href", url)

    }
    // $("#collegium").on('click', function(){

    // $("modal.title").
    // });
</script>
@endsection

resources/views/mail.blade.php
@extends('layouts.app')

@section('page_name', __('messages.Compose'))

@section('custom_header')
    <link rel="stylesheet" href="{{asset('vendor/bootstrap-fileupload/bootstrap-fileupload.min.css')}}" />
    <link rel="stylesheet" href="{{asset('vendor/bootstrap-multiselect/css/bootstrap-multiselect.css')}}" />
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <h3>asd</h3>
        </div>
    </div>
    <section class=" content-with-menu-has-toolbar mailbox mt-lg">
        <div class="content-with-menu-container" data-mailbox data-mailbox-view="compose">
            <form method="POST" action="{{ route('sendmail') }}" class="col-md-12" enctype="multipart/form-data">
                @csrf
                <div class="inner-toolbar clearfix">
                    <ul>
                        <li>
                            <button type="submit" class="btn btn-dark btn-md pt-2 pb-2 text-3" ><i class="far fa-paper-plane mr-2"></i> {{__('messages.Send')}}</button>
                        </li>
                        <li>
                            <a href="/"><i class="fas fa-times mr-2"></i> {{__('messages.Discard')}}</a>
                        </li>
                    </ul>
                </div>
                <div class="mailbox-compose ">
                    <div class="form-horizontal form-bordered form-bordered">
                        <div class="form-group">
                            <div class="form-group row mr-4">
                            <label class=" col-lg-1 control-label text-lg-right pt-3 ">{{__('messages.To')}}<span class="required">*</span></label>
                            <div class="col-lg-6 mr-lg-4">
                                @if($collegium_id != null)
                                    <select required name="user_ids[]" class="form-control" multiple="multiple" data-plugin-multiselect data-plugin-options='{ "maxHeight": 200, "includeSelectAllOption": true }' id="ms_example5">
                                        <optgroup label="{{ Str::limit($selectedCollegium->title, 50 )}}">
                                            @foreach($selectedCollegium->officials as $user)
                                                <option value="{{$user->id}}" selected>{{$user->name.' '.$user->last_name.' - '. $user->email}}</option>
                                            @endforeach
                                        </optgroup>
                                    </select>
                                @else
                                    <select required name="user_ids[]" class="form-control" multiple="multiple" data-plugin-multiselect data-plugin-options='{ "maxHeight": 200, "includeSelectAllOption": true }' id="ms_example5">
                                        @foreach($collegiums as $collegium)
                                        <optgroup label="{{ Str::limit($collegium->title, 43 )}}">
                                            @foreach($collegium->officials as $user)
                                            <option value="{{$user->id}}">{{$user->name.' '.$user->last_name.' - '. $user->email}}</option>
                                            @endforeach
                                        </optgroup>
                                        @endforeach
                                    </select>
                                @endif
                                </div>
                            </div>
                        </div>
                        <div class="form-group form-group-invisible">
                            <label for="subject" class="control-label-invisible pt-2">{{__('messages.Subject')}}<span class="required">*</span></label>
                            <div class="col-md-12 mailbox-compose-field">
                                <input required id="subject" type="text" class="form-control form-control-invisible" name="subject">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="compose">
                                <label for="Body" class="control-label-invisible">{{__('messages.Body')}}<span class="required">*</span></label>
                                <textarea required name="body" class="form-control" rows="3" id="textareaAutosize" data-plugin-textarea-autosize="" style="overflow: hidden; overflow-wrap: break-word; resize: none; height: 89px;"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                           <div class="form-group row ml-3">
                            <label class=" col-lg-1 control-label text-lg-right pt-3 ">{{__('messages.Attach File')}}:</label>
                            <div class="col-lg-6 mr-lg-4">
                                <div class="fileupload fileupload-new"  data-provides="fileupload"><input type="hidden" >
                                    <div class="input-append">
                                        <div class="uneditable-input">
                                            <i class="fas fa-file fileupload-exists"></i>
                                            <span class="fileupload-preview"></span>
                                        </div>
                                        <span id="clearbtn" class="btn btn-default btn-file">
                                            <span class="fileupload-exists">{{__('messages.Change')}}</span>
                                            <span class="fileupload-new">{{__('messages.Zgjidh')}}</span>
                                            <input id="input" type="file" name="file">
                                        </span>
                                        <a href="#" id="dismiss" class="btn btn-default fileupload-exists" data-dismiss="fileupload">{{__('messages.Remove')}}</a>
                                    </div>
                                </div>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
@endsection

@section('custom_footer')
    <script src="{{asset('vendor/bootstrap-fileupload/bootstrap-fileupload.min.js')}}"></script>
    <script src="{{asset('vendor/bootstrap-multiselect/js/bootstrap-multiselect.js')}}"></script>
    <script src="{{asset('js/examples/examples.advanced.form.js')}}"></script>
@endsection

resources/views/showCity.blade.php
@extends('layouts.app')

@section('page_name', __('messages.Officials').' '.ucfirst($city->name))

@section('custom_header')
    <link rel="stylesheet" href="{{asset('vendor/select2/css/select2.css')}}" />
    <link rel="stylesheet" href="{{asset('vendor/select2-bootstrap-theme/select2-bootstrap.min.css')}}" />
    <link rel="stylesheet" href="{{asset('vendor/datatables/media/css/dataTables.bootstrap4.css')}}" />
@endsection

@section('content')
        <section class="card">

            <header class="card-header">
                <div class="card-actions">
                    <a href="#" class="card-action card-action-toggle" data-card-toggle></a>
                    <a href="#" class="card-action card-action-dismiss" data-card-dismiss></a>
                </div>

                <h2 class="card-title" style="text-transform: capitalize;">{{__('messages.Officials')}} {{ucfirst($city->name)}} - {{count($city->officials)}}</h2>

            </header>
            <div class="card-body">

                 <table class="table table-bordered table-striped mb-0" id="datatable-editable">
            <thead>
            <tr>
                <th>{{__('messages.Emri')}}</th>
                <th>{{__('messages.Collegium')}}</th>
                <th>{{__('Email')}}</th>
                <th>{{__('messages.Phone Number')}}</th>
                <th>{{__('messages.Actions')}}</th>
            </tr>
            </thead>
            <tbody>
            @forelse($city->officials as $official)
                <tr data-item-id="{{$official->id}}" role="row" class="odd">
                    <td>{{$official->name}} {{$official->last_name}}</td>
                     <td>@if(!$official->collegium)
                           <p style="color:red">Null</p>
                        @else
                            {{$official->collegium->title}}
                        @endif
                    </td>
                    <td>{{$official->email}}</td>
                    <td>{{$official->phone}}</td>
                    <td class="actions">
                        <form id="delete-form {{$official->id}}" class="hidden" method="POST" action="{{route('official.destroy', $official->id)}}">
                            @csrf
                            @method('delete')
                            <button type="submit" class="hidden" id="{{$official->id}}"></button>
                        </form>
                        <a data-toggle="tooltip" title="" href="#" data-original-title="{{__('Arkivo Zyrëtarin')}}" onclick="archive({{$official->id}})" class="delete on-default"><i class="fa fa-archive"></i></a>
                    </td>
                </tr>
            @empty
                <tr class="odd"><td valign="top" colspan="4" class="dataTables_empty">{{__('messages.No data available in table')}}</td></tr>
                @endforelse
            </tbody>
        </table>
            </div>

        </section>
@endsection

@section('custom_footer')
    <script src="{{asset('vendor/select2/js/select2.js')}}"></script>
    <script src="{{asset('vendor/datatables/media/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('vendor/datatables/media/js/dataTables.bootstrap4.min.js')}}"></script>
 <script src="{{asset('vendor/datatables/extras/TableTools/Buttons-1.4.2/js/buttons.print.js')}}"></script>
    <script src="{{asset('vendor/datatables/extras/TableTools/Buttons-1.4.2/js/dataTables.buttons.js')}}"></script>
    <script>

(function($) {

	'use strict';

	var EditableTable = {

		options: {
			addButton: '#addToTable',
			table: '#datatable-editable',
			dialog: {
				wrapper: '#dialog',
				cancelButton: '#dialogCancel',
				confirmButton: '#dialogConfirm',
			}
		},

		initialize: function() {
			this
				.setVars()
				.build()
				.events();
		},

		setVars: function() {
			this.$table				= $( this.options.table );
			this.$addButton			= $( this.options.addButton );

			// dialog
			this.dialog				= {};
			this.dialog.$wrapper	= $( this.options.dialog.wrapper );
			this.dialog.$cancel		= $( this.options.dialog.cancelButton );
			this.dialog.$confirm	= $( this.options.dialog.confirmButton );

			return this;
		},

		build: function() {
			this.datatable = this.$table.DataTable({
				dom: '<"row"<"col-lg-6"l><"col-lg-6"f>><"table-responsive"t> Bp ',
				aoColumns: [
					null,
					null,
					null,
					null,
					{ "bSortable": false }
				],

			});

			window.dt = this.datatable;

			return this;
		},
	};

	$(function() {
		EditableTable.initialize();
	});

}).apply(this, [jQuery]);
        function archive(id){
            $("#"+id).click();
        }
        $(document).ready(function (){
        $(".dt-button").addClass('btn btn-primary')
        });
    </script>
@endsection