routes/web.php
<?php

use App\Jobs\SendEmailsJob;
use App\Mail\NewUser;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Mail;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//dashboard - home.blade.php
Route::group(['middleware' => 'forceSSL'], function() {

//change language
Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
});
//user needs to be logged in routes
Route::group(['middleware' => 'auth'], function(){
    Route::get('/', 'HomeController@index')->name('home');

    //mail routes
    Route::get('/mail/{collegium_id?}', 'MailController@index');
    Route::post('/sendmail', 'MailController@sendMailToOneUser')->name('sendmail');
    //zyrtaret
    Route::get('/officials/{city}', 'OfficialController@showByCity');
    Route::get('/official/archive', 'OfficialController@archiveIndex')->name('archive');
    Route::resource('/official', 'OfficialController');
    Route::patch('/official/{id}/ndrysho', 'OfficialController@ndrysho')->name('official.ndrysho');
    Route::patch('/official/{id}/headship', 'OfficialController@addToHeadShip')->name('addToHeadShip');
    Route::patch('/official/{id}/headship/remove', 'OfficialController@removeFromHeadship')->name('removeFromHeadship');
    //kolegjiumet
    Route::resource('/collegium', 'CollegiumController');
    //komunat
    Route::get('/municipalities', 'MunicipalityController@index');
    //perdoruesit
    Route::resource('/user', 'UserController');

    //calendar
    Route::group(['prefix' => 'calendar/'], function () {
        Route::get('/', 'CalendarController@index');
        Route::post('/action', 'CalendarController@action');
    });

    //file-storage
    Route::group(['prefix' => 'file/'], function () {
        Route::get('/', 'FileController@index');
        Route::get('/create', 'FileController@create');
        Route::post('/store', 'FileController@store')->name('store.image');
        Route::get('/{id}/download', 'FileController@download')->name('download.image');
        Route::delete('/{id}/delete', 'FileController@destroy')->name('delete.image');
    });

    Route::get('/logout', 'Auth\LoginController@logout');
});
//Auth::routes(['register' => false]);

Auth::routes();

Route::get('/register', function (){
   return redirect('login');
});
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreUserRequest;
use App\Http\Requests\UserUpdateRequest;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Session\Store;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{

    public function index()
    {
        return view('user.profile');
    }

    public function create()
    {
        return view('user.create');
    }

    public function store(StoreUserRequest  $request)
    {
        $user = New User;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = bcrypt($request->password);
        $user->save();
        return redirect()->back()->with(['status'=> __('messages.Created Successfully')]);
    }

    public function update(UserUpdateRequest $request)
    {
        $this->validate($request,['old_password' => [
            'required', function ($attribute, $value, $fail) {
                if (!Hash::check($value, auth()->user()->password)) {
                    $fail(__('messages.Old Password didn\'t match'));
                }
            },
        ]]);
        $user = auth()->user();

        $user->name = $request->name;
        $user->email = $request->email;

        if($request->password){

            $user->password = bcrypt($request->password);
        }
        $user->save();
        return redirect()->back()->with(['status'=>__('messages.Updated Successfully')]);
    }

    public function destroy($id)
    {
        $user = auth()->user();
        $user->delete();
        return redirect()->back();
    }

}

resources/views/user/create.blade.php
@extends('layouts.app')

@section('page_name', __('messages.add user'))

@section('custom_header')
    <link rel="stylesheet" href="{{asset('vendor/boxicons/css/boxicons.min.css')}}" />
@endsection

@section('content')
    <div class="col-lg-8 col-xl-6 ">

        <div class="col-lg-12">
            <form id="form" action="{{route('user.store')}}" class="form-horizontal" method="POST">
                @csrf
                @method('POST')
                <section class="card">
                    <header class="card-header">
                        <div class="card-actions">
                            <a href="#" class="card-action card-action-toggle" data-card-toggle=""></a>
                            <a href="#" class="card-action card-action-dismiss" data-card-dismiss=""></a>
                        </div>

                        <h2 class="card-title">{{__('messages.add user')}}</h2>
                        <p class="card-subtitle">
                            {{__('messages.infoUserEdit')}}
                        </p>
                    </header>
                    <div class="card-body" style="display: block;">
                        <div class="form-group row">
                            <label class="col-sm-3 control-label text-sm-right pt-2">{{__('messages.Full Name:')}}<span class="required">*</span></label>
                            <div class="col-sm-4">
                                <input type="text" name="name" class="form-control" placeholder="{{__('messages.Emri Mbiemri:')}}" required value="{{old('name')}}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-3 control-label text-sm-right pt-2">E-mail: <span class="required">*</span></label>
                            <div class="col-sm-7">
                                <div class="input-group">
													<span class="input-group-prepend">
														<span class="input-group-text">
															<i class="fas fa-envelope"></i>
														</span>
													</span>
                                    <input type="email" name="email" class="form-control" placeholder="email@email.com" required value="{{old('email')}}">
                                </div>
                            </div>
                            <div class="col-sm-9">

                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-3 control-label text-sm-right pt-2">Password: </label>
                            <div class="col-sm-6">
                                <input type="password" name="password" class="form-control">
                            </div>
                        </div>
                    </div>
                    <footer class="card-footer" style="display: block;">
                        <div class="row justify-content-end">
                            <div class="col-sm-9">
                                <button type="submit" class="btn btn-primary">{{__('messages.Submit')}}</button>
                                <button type="reset" class="btn btn-default">{{__('messages.Reset')}}</button>
                            </div>
                        </div>
                    </footer>
                </section>
            </form>



        </div>


    </div>
@endsection

@section('custom_footer')
    <script>

        $( document ).ready(function() {
            var locale = '{{ config('app.locale') }}';
            var message = "This field is required."
            if (locale == 'sq'){
                message = "Kjo fushe nuk mund te jete e zbrazet";
            }else if(locale == 'sr'){
                message = "Ovo polje je obavezno.";
            }
            $.extend($.validator.messages, {
                required: message,
            });
        });
    </script>
    <script src="{{asset('vendor/autosize/autosize.js')}}"></script>
    <script src="{{asset('vendor/bootstrap-fileupload/bootstrap-fileupload.min.js')}}"></script>
    <script src="{{asset('vendor/jquery-validation/jquery.validate.js')}}"></script>
    <script src="{{asset('vendor/pnotify/pnotify.custom.js')}}"></script>
    <script src="{{asset('vendor/bootstrap-wizard/jquery.bootstrap.wizard.js')}}"></script>
    <script src="{{asset('js/examples/examples.wizard.js')}}"></script>

@endsection

resources/views/user/profile.blade.php
@extends('layouts.app')

@section('page_name', __('messages.User Profile'))

@section('custom_header')
    <link rel="stylesheet" href="{{asset('vendor/boxicons/css/boxicons.min.css')}}" />
@endsection

@section('content')
<div class="col-lg-8 col-xl-6 ">

    <div class="col-lg-12">
        <form id="form" action="{{route('user.update', auth()->user())}}" class="form-horizontal" method="POST">
            @csrf
            @method('PATCH')
            <section class="card">
                <header class="card-header">
                    <div class="card-actions">
                        <a href="#" class="card-action card-action-toggle" data-card-toggle=""></a>
                        <a href="#" class="card-action card-action-dismiss" data-card-dismiss=""></a>
                    </div>

                    <h2 class="card-title">{{__('messages.User Profile')}}</h2>
                    <p class="card-subtitle">
                        {{__('messages.infoUserEdit')}}
                    </p>
                </header>
                <div class="card-body" style="display: block;">
                    <div class="form-group row">
                        <label class="col-sm-3 control-label text-sm-right pt-2">Full Name <span class="required">*</span></label>
                        <div class="col-sm-4">
                            <input type="text" name="name" class="form-control" required value="{{auth()->user()->name}}"  >
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 control-label text-sm-right pt-2">Email <span class="required">*</span></label>
                        <div class="col-sm-7">
                            <div class="input-group">
													<span class="input-group-prepend">
														<span class="input-group-text">
															<i class="fas fa-envelope"></i>
														</span>
													</span>
                                <input type="email" name="email" class="form-control" required value="{{auth()->user()->email}}">
                            </div>
                        </div>
                        <div class="col-sm-9">

                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 control-label text-sm-right pt-2">Old Password </label>
                        <div class="col-sm-6">
                            <input type="password" name="old_password" class="form-control">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 control-label text-sm-right pt-2">New Password </label>
                        <div class="col-sm-6">
                            <input type="password" name="password" class="form-control">
                        </div>
                    </div>
                </div>
                <footer class="card-footer" style="display: block;">
                    <div class="row justify-content-end">
                        <div class="col-sm-9">
                            <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                            <button type="reset" class="btn btn-default">Reset</button>
                             <form method="POST" action="{{route('user.destroy', auth()->user()->id)}}">
                                 @method('delete')
                                @csrf
                            <button type="submit" class="btn btn-danger ml-xs">Delete Account</button>
                        </form>
                        </div>
                    </div>
                </footer>
            </section>


    </div>


</div>
@endsection

@section('custom_footer')
    <script>

        $( document ).ready(function() {
            var locale = '{{ config('app.locale') }}';
            var message = "This field is required."
            if (locale == 'sq'){
                message = "Kjo fushe nuk mund te jete e zbrazet";
            }else if(locale == 'sr'){
                message = "Ovo polje je obavezno.";
            }
            $.extend($.validator.messages, {
                required: message,
            });
        });
    </script>
    <script src="{{asset('vendor/autosize/autosize.js')}}"></script>
    <script src="{{asset('vendor/bootstrap-fileupload/bootstrap-fileupload.min.js')}}"></script>
    <script src="{{asset('vendor/jquery-validation/jquery.validate.js')}}"></script>
    <script src="{{asset('vendor/pnotify/pnotify.custom.js')}}"></script>
    <script src="{{asset('vendor/bootstrap-wizard/jquery.bootstrap.wizard.js')}}"></script>
    <script src="{{asset('js/examples/examples.wizard.js')}}"></script>

@endsection