routes/web.php
<?php

use App\Jobs\SendEmailsJob;
use App\Mail\NewUser;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Mail;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//dashboard - home.blade.php
Route::group(['middleware' => 'forceSSL'], function() {

//change language
Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
});
//user needs to be logged in routes
Route::group(['middleware' => 'auth'], function(){
    Route::get('/', 'HomeController@index')->name('home');

    //mail routes
    Route::get('/mail/{collegium_id?}', 'MailController@index');
    Route::post('/sendmail', 'MailController@sendMailToOneUser')->name('sendmail');
    //zyrtaret
    Route::get('/officials/{city}', 'OfficialController@showByCity');
    Route::get('/official/archive', 'OfficialController@archiveIndex')->name('archive');
    Route::resource('/official', 'OfficialController');
    Route::patch('/official/{id}/ndrysho', 'OfficialController@ndrysho')->name('official.ndrysho');
    Route::patch('/official/{id}/headship', 'OfficialController@addToHeadShip')->name('addToHeadShip');
    Route::patch('/official/{id}/headship/remove', 'OfficialController@removeFromHeadship')->name('removeFromHeadship');
    //kolegjiumet
    Route::resource('/collegium', 'CollegiumController');
    //komunat
    Route::get('/municipalities', 'MunicipalityController@index');
    //perdoruesit
    Route::resource('/user', 'UserController');

    //calendar
    Route::group(['prefix' => 'calendar/'], function () {
        Route::get('/', 'CalendarController@index');
        Route::post('/action', 'CalendarController@action');
    });

    //file-storage
    Route::group(['prefix' => 'file/'], function () {
        Route::get('/', 'FileController@index');
        Route::get('/create', 'FileController@create');
        Route::post('/store', 'FileController@store')->name('store.image');
        Route::get('/{id}/download', 'FileController@download')->name('download.image');
        Route::delete('/{id}/delete', 'FileController@destroy')->name('delete.image');
    });

    Route::get('/logout', 'Auth\LoginController@logout');
});
//Auth::routes(['register' => false]);

Auth::routes();

Route::get('/register', function (){
   return redirect('login');
});
});

app/Models/Collegium.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;

class Collegium extends Model implements TranslatableContract
{
    use Translatable;
    protected $table = 'collegiums';
    protected $fillable = ['filename', 'filetype', 'filesize', 'filepath', 'image'];
    public $translatedAttributes = ['title', 'description'];

    public function officials()
    {
        return $this->hasMany('App\Models\Official');
    }
}

app/Http/Controllers/CollegiumController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CollegiumStoreRequest;
use App\Models\Collegium;
use Illuminate\Http\Request;

class CollegiumController extends Controller
{

    public function index()
    {
        $collegiums = Collegium::all();
        return view('collegium.index', compact('collegiums'));
    }
    public function create()
    {
        return view('collegium.create');
    }

    public function store(CollegiumStoreRequest $request)
    {
        $img = $request->file('image');
                $directoryName ='files/collegium';
                 if (!is_dir($directoryName)) {
                    mkdir($directoryName, 0700, true);
                 }
                 $file_name = uniqid().'-'.time().'.'.$img->getClientOriginalExtension();
                 $file_type = $img->getClientOriginalExtension();
                 $file_size = $img->getSize();
                 $file_path = 'files/collegium/'.$file_name;
                 $request->file('image')->move('files/collegium', $file_name);
        Collegium::create([
            'en' => [
                'title'       => $request->en_title,
                'description'       => $request->en_description
            ],
            'sq' => [
                'title'       => $request->sq_title,
                'description'       => $request->sq_description
            ],
            'sr' => [
                'title'       => $request->sr_title,
                'description'       => $request->sr_description
            ],
            'filename' => $file_name,
            'filetype' => $file_type,
            'filesize' => $file_size,
            'filepath' => $directoryName,
            'image' => $file_path
        ]);
        return redirect()->route('collegium.index')->with(['status' => __('messages.Created Successfully')]);
    }

    public function show($id)
    {
        $collegium = Collegium::findOrFail($id);
        $headships = $collegium->officials->where('headship', true);
        return view('collegium.show', compact(['collegium', 'headships']));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Collegium  $collegium
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $collegium = Collegium::findOrFail($id);
        return view('collegium.edit', compact('collegium'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Collegium  $collegium
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Collegium::findOrFail($id)->update([
            'en' => [
                'title'       => $request->en_title,
                'description'       => $request->en_description
            ],
            'sq' => [
                'title'       => $request->sq_title,
                'description'       => $request->sq_description
            ],
            'sr' => [
                'title'       => $request->sr_title,
                'description'       => $request->sr_description
            ],
        ]);
        return redirect()->route('collegium.index')->with(['status' => __('messages.Updated Successfully')]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Collegium  $collegium
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Collegium::findOrFail($id)->delete();
        return redirect()->route('collegium.index')->with(['danger' => __('messages.Deleted Successfully')]);
    }
}

resources/views/collegium/create.blade.php
@extends('layouts.app')

@section('page_name', __('messages.Create Collegium'))

@section('custom_header')
    <link rel="stylesheet" href="{{asset('vendor/boxicons/css/boxicons.min.css')}}" />
    <link rel="stylesheet" href="{{asset('vendor/bootstrap-fileupload/bootstrap-fileupload.min.css')}}" />
@endsection

@section('content')

    <div class="col-lg-6 m-auto">
        <section class="card form-wizard" id="w1">
            <header class="card-header">
                <div class="card-actions">
                    <a href="#" class="card-action card-action-toggle" data-card-toggle=""></a>
                    <a href="#" class="card-action card-action-dismiss" data-card-dismiss=""></a>
                </div>

                <h2 class="card-title">{{__('messages.Create Collegium')}}</h2>
            </header>
            <div class="card-body card-body-nopadding">
                <div class="wizard-tabs">
                    <ul class="nav wizard-steps">
                        <li class="nav-item active">
                            <a href="#w1-account" data-toggle="tab" class="nav-link text-center">
                                <span class="badge">1</span>
                                {{__('messages.English')}}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#w1-profile" data-toggle="tab" class="nav-link text-center">
                                <span class="badge">2</span>
                                {{__('messages.Albanian')}}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#w1-confirm" data-toggle="tab" class="nav-link text-center">
                                <span class="badge">3</span>
                                {{__('messages.Serbian')}}
                            </a>
                        </li>
                    </ul>
                </div>
                <form id="myForm" class="form-horizontal" method="POST" action="{{route('collegium.store')}}" enctype="multipart/form-data">
                    @csrf
                    <div class="tab-content">
                        <div id="w1-account" class="tab-pane p-3 active">
                            <div class="form-group row">
                                <label class="col-sm-4 control-label text-sm-right pt-1" for="w1-username">{{__('messages.Title (EN)')}}
                                    <span class="required">*</span></label>

                                <div class="col-sm-8">
                                    <input type="text" class="form-control" name="en_title" id="w1-username" required value="{{ old('en_title') }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-4 control-label text-sm-right pt-1" for="w1-password">{{__('messages.Description (EN)')}}</label>
                                <div class="col-sm-8">
                                    <textarea class="form-control" rows="3" id="textareaAutosize" data-plugin-textarea-autosize="" style="overflow: hidden; overflow-wrap: break-word; resize: none; height: 89px;" name="en_description" id="w1-username" value="{{ old('en_description') }}"></textarea>
                                </div>
                            </div>
                             <div class="form-group row">
                                                <label class="col-lg-4 control-label text-lg-right pt-1">{{__('messages.File Upload')}} <span class="required">*</span></label>
                                                <div class="col-lg-8">
                                                    <div class="fileupload fileupload-new"  data-provides="fileupload"><input type="hidden" >
                                                        <div class="input-append">
                                                            <div class="uneditable-input">
                                                                <i class="fas fa-file fileupload-exists"></i>
                                                                <span class="fileupload-preview"></span>
                                                            </div>
                                                            <span class="btn btn-default btn-file">
                                                                <span class="fileupload-exists">{{__('messages.Change')}}</span>
                                                                <span class="fileupload-new">{{__('messages.Select file')}}</span>
                                                                <input type="file" name="image" required>
                                                            </span>
                                                            <a href="#" class="btn btn-default fileupload-exists" data-dismiss="fileupload">{{__('messages.Remove')}}</a>
                                                        </div>
                                                    </div>
                                                </div>
                                </div>
                        </div>
                        <div id="w1-profile" class="tab-pane p-3">
                            <div class="form-group row">
                                <label class="col-sm-4 control-label text-sm-right pt-1" for="w1-username">{{__('messages.Title (SQ)')}}<span class="required">*</span></label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" name="sq_title" id="w1-username" required="" value="{{ old('sq_title') }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-4 control-label text-sm-right pt-1" for="w1-password">{{__('messages.Description (SQ)')}}</label>
                                <div class="col-sm-8">
                                    <textarea class="form-control" rows="3" id="textareaAutosize" data-plugin-textarea-autosize="" style="overflow: hidden; overflow-wrap: break-word; resize: none; height: 89px;"  name="sq_description" id="w1-username" value="{{ old('sq_description') }}"></textarea>
                                </div>
                            </div>
                        </div>
                        <div id="w1-confirm" class="tab-pane p-3" id="last">
                            <div class="form-group row">
                                <label class="col-sm-4 control-label text-sm-right pt-1" for="w1-username">{{__('messages.Title (SR)')}} <span class="required">*</span></label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" name="sr_title" id="w1-username" required="" value="{{ old('sr_title') }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-4 control-label text-sm-right pt-1" for="w1-password">{{__('messages.Description (SR)')}}</label>
                                <div class="col-sm-8">
                                    <textarea class="form-control" rows="3" id="textareaAutosize" data-plugin-textarea-autosize="" style="overflow: hidden; overflow-wrap: break-word; resize: none; height: 89px;"  name="sr_description" id="w1-username"  value="{{ old('sr_description') }}"></textarea>
                                </div>
                            </div>

                        </div>
                    </div>
                </form>

            </div>
            <div class="card-footer">
                <ul class="pager">
                    <li class="previous disabled">
                        <a><i class="fas fa-angle-left"></i> {{__('messages.Previous')}}</a>
                    </li>
                    <li class="finish hidden float-right">
                        <button id="butoni" type="submit" class="btn btn-default">{{__('messages.Finish')}}</button>
                    </li>
                    <li class="next">
                        <a id="next">{{__('messages.Next')}} <i class="fas fa-angle-right"></i></a>
                    </li>
                </ul>
            </div>

        </section>

    </div>


@endsection
@section('custom_footer')
    <script>
        $( document ).ready(function() {
            var locale = '{{ config('app.locale') }}';
            var message = "This field is required."
            if (locale == 'sq'){
                 message = "Kjo fushe nuk mund te jete e zbrazet";
            }else if(locale == 'sr'){
                 message = "Ovo polje je obavezno.";
            }
            $.extend($.validator.messages, {
                required: message,
            });
        });
    </script>
    <script src="{{asset('vendor/autosize/autosize.js')}}"></script>
    <script src="{{asset('vendor/bootstrap-fileupload/bootstrap-fileupload.min.js')}}"></script>
    <script src="{{asset('vendor/jquery-validation/jquery.validate.js')}}"></script>
    <script src="{{asset('vendor/pnotify/pnotify.custom.js')}}"></script>
    <script src="{{asset('vendor/bootstrap-wizard/jquery.bootstrap.wizard.js')}}"></script>
    <script src="{{asset('js/examples/examples.wizard.js')}}"></script>

@endsection

resources/views/collegium/edit.blade.php
@extends('layouts.app')

@section('page_name', __('messages.Edit Collegium'))

@section('custom_header')
    <link rel="stylesheet" href="{{asset('vendor/boxicons/css/boxicons.min.css')}}" />
    <link rel="stylesheet" href="{{asset('vendor/bootstrap-fileupload/bootstrap-fileupload.min.css')}}" />
@endsection

@section('content')

    <div class="col-lg-6 m-auto">
        <section class="card form-wizard" id="w1">
            <header class="card-header">
                <div class="card-actions">
                    <a href="#" class="card-action card-action-toggle" data-card-toggle=""></a>
                    <a href="#" class="card-action card-action-dismiss" data-card-dismiss=""></a>
                </div>

                <h2 class="card-title">{{__('messages.Create Collegium')}}</h2>
            </header>
            <div class="card-body card-body-nopadding">
                <div class="wizard-tabs">
                    <ul class="nav wizard-steps">
                        <li class="nav-item active">
                            <a href="#w1-account" data-toggle="tab" class="nav-link text-center">
                                <span class="badge">1</span>
                                {{__('messages.English')}}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#w1-profile" data-toggle="tab" class="nav-link text-center">
                                <span class="badge">2</span>
                                {{__('messages.Albanian')}}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#w1-confirm" data-toggle="tab" class="nav-link text-center">
                                <span class="badge">3</span>
                                {{__('messages.Serbian')}}
                            </a>
                        </li>
                    </ul>
                </div>
                <form id="myForm" class="form-horizontal" method="POST" action="{{route('collegium.update', $collegium->id)}}">
                    @csrf
                    @method('PATCH')
                    <div class="tab-content">
                        <div id="w1-account" class="tab-pane p-3 active">
                            <div class="form-group row">
                                <label class="col-sm-4 control-label text-sm-right pt-1" for="w1-username">{{__('messages.Title (EN)')}}
                                    <span class="required">*</span></label>

                                <div class="col-sm-8">
                                    <input type="text" class="form-control" name="en_title" id="w1-username" required value="{{ $collegium->translate('en')->title }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-4 control-label text-sm-right pt-1" for="w1-password">{{__('messages.Description (EN)')}}</label>
                                <div class="col-sm-8">
                                    <textarea class="form-control" rows="3" id="textareaAutosize" data-plugin-textarea-autosize="" style="overflow: hidden; overflow-wrap: break-word; resize: none; height: 89px;" name="en_description" id="w1-username" >{{$collegium->translate('en')->description }}</textarea>
                                </div>
                            </div>
                        </div>
                        <div id="w1-profile" class="tab-pane p-3">
                            <div class="form-group row">
                                <label class="col-sm-4 control-label text-sm-right pt-1" for="w1-username">{{__('messages.Title (SQ)')}}<span class="required">*</span></label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" name="sq_title" id="w1-username" required="" value="{{ $collegium->translate('sq')->title }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-4 control-label text-sm-right pt-1" for="w1-password">{{__('messages.Description (SQ)')}}</label>
                                <div class="col-sm-8">
                                    <textarea class="form-control" rows="3" id="textareaAutosize" data-plugin-textarea-autosize="" style="overflow: hidden; overflow-wrap: break-word; resize: none; height: 89px;"  name="sq_description" id="w1-username">{{ $collegium->translate('sq')->description }}</textarea>
                                </div>
                            </div>
                        </div>
                        <div id="w1-confirm" class="tab-pane p-3" id="last">
                            <div class="form-group row">
                                <label class="col-sm-4 control-label text-sm-right pt-1" for="w1-username">{{__('messages.Title (SR)')}} <span class="required">*</span></label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" name="sr_title" id="w1-username" required="" value="{{ $collegium->translate('sr')->title }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-4 control-label text-sm-right pt-1" for="w1-password">{{__('messages.Description (SR)')}}</label>
                                <div class="col-sm-8">
                                    <textarea class="form-control" rows="3" id="textareaAutosize" data-plugin-textarea-autosize="" style="overflow: hidden; overflow-wrap: break-word; resize: none; height: 89px;"  name="sr_description" id="w1-username" >{{ $collegium->translate('sr')->description }}</textarea>
                                </div>
                            </div>

                        </div>
                    </div>
                </form>

            </div>
            <div class="card-footer">
                <ul class="pager">
                    <li class="previous disabled">
                        <a><i class="fas fa-angle-left"></i> {{__('messages.Previous')}}</a>
                    </li>
                    <li class="finish hidden float-right">
                        <button id="butoni" type="submit" class="btn btn-default">{{__('messages.Finish')}}</button>
                    </li>
                    <li class="next">
                        <a id="next">{{__('messages.Next')}} <i class="fas fa-angle-right"></i></a>
                    </li>
                </ul>
            </div>

        </section>

    </div>


@endsection
@section('custom_footer')
    <script>
        $( document ).ready(function() {
            var locale = '{{ config('app.locale') }}';
            var message = "This field is required."
            if (locale == 'sq'){
                 message = "Kjo fushe nuk mund te jete e zbrazet";
            }else if(locale == 'sr'){
                 message = "Ovo polje je obavezno.";
            }
            $.extend($.validator.messages, {
                required: message,
            });
        });
    </script>
    <script src="{{asset('vendor/autosize/autosize.js')}}"></script>
    <script src="{{asset('vendor/bootstrap-fileupload/bootstrap-fileupload.min.js')}}"></script>
    <script src="{{asset('vendor/jquery-validation/jquery.validate.js')}}"></script>
    <script src="{{asset('vendor/pnotify/pnotify.custom.js')}}"></script>
    <script src="{{asset('vendor/bootstrap-wizard/jquery.bootstrap.wizard.js')}}"></script>
    <script src="{{asset('js/examples/examples.wizard.js')}}"></script>

@endsection

resources/views/collegium/index.blade.php
@extends('layouts.app')

@section('page_name', __('messages.Collegiums'))

@section('custom_header')
    <link rel="stylesheet" href="{{asset('vendor/select2/css/select2.css')}}" />
    <link rel="stylesheet" href="{{asset('vendor/select2-bootstrap-theme/select2-bootstrap.min.css')}}" />
    <link rel="stylesheet" href="{{asset('vendor/datatables/media/css/dataTables.bootstrap4.css')}}" />
@endsection

@section('content')
        <section class="card">

            <header class="card-header">
                <div class="card-actions">
                    <a href="#" class="card-action card-action-toggle" data-card-toggle></a>
                    <a href="#" class="card-action card-action-dismiss" data-card-dismiss></a>
                </div>

                <h2 class="card-title">{{__('messages.Collegiums')}}   <a href="{{route('collegium.create')}}" class="btn btn-sm btn-dark">{{__('messages.Create Collegium')}}   <i class="fas fa-plus"></i></a></h2>
            </header>
            <div class="card-body">
                <table class="table table-bordered table-striped mb-0" id="datatable-editable">
                    <thead>
                    <tr>
                        <th>Logo</th>
                        <th>{{__('messages.Kolegjiumi')}}</th>
                        <th>{{__('messages.Description')}}</th>
                        <th>{{__('messages.Actions')}}</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($collegiums as $collegium)
                        <tr data-item-id="{{$collegium->id}}" role="row" class="odd">
                        <td class="sorting_1"><img src="{{asset($collegium->image)}}" width="20" height="20"></td>

                        <td><a data-toggle="tooltip" title="" href="{{route('collegium.show', $collegium->id)}}" data-original-title="{{__('messages.Seemore')}}"> {{$collegium->title}}</a></td>
                        <td>{{Str::limit($collegium->description, 45)}}</td>
                        <td class="actions">
                            <form id="delete-form {{$collegium->id}}" class="hidden" action="{{route('collegium.destroy', $collegium->id)}}" method="POST">
                                @csrf
                                @method('Delete')
                                <button type="submit" class="hidden" id="{{$collegium->id}}"></button>
                            </form>
                            <a href="{{route('collegium.edit', $collegium->id)}}" class="edit on-default"><i class="fas fa-pencil-alt"></i></a>
                            <a href="#" onclick="destroy({{$collegium->id}})" class="delete on-default"><i class="far fa-trash-alt"></i></a>
                        </td>
                    </tr>
                    @empty
                        <tr class="odd"><td valign="top" colspan="4" class="dataTables_empty">{{__('messages.No data available in table')}}</td></tr>
                        @endforelse
                    </tbody>
                </table>
            </div>

        </section>
@endsection

@section('custom_footer')
    <script src="{{asset('vendor/select2/js/select2.js')}}"></script>
    <script src="{{asset('vendor/datatables/media/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('vendor/datatables/media/js/dataTables.bootstrap4.min.js')}}"></script>
    <script src="{{asset('js/examples/examples.datatables.editable.js')}}"></script>
    <script>

        function destroy(id){
            $("#"+id).click();
        }

    </script>

@endsection