routes/web.php
<?php

use App\Jobs\SendEmailsJob;
use App\Mail\NewUser;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Mail;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//dashboard - home.blade.php
Route::group(['middleware' => 'forceSSL'], function() {

//change language
Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
});
//user needs to be logged in routes
Route::group(['middleware' => 'auth'], function(){
    Route::get('/', 'HomeController@index')->name('home');

    //mail routes
    Route::get('/mail/{collegium_id?}', 'MailController@index');
    Route::post('/sendmail', 'MailController@sendMailToOneUser')->name('sendmail');
    //zyrtaret
    Route::get('/officials/{city}', 'OfficialController@showByCity');
    Route::get('/official/archive', 'OfficialController@archiveIndex')->name('archive');
    Route::resource('/official', 'OfficialController');
    Route::patch('/official/{id}/ndrysho', 'OfficialController@ndrysho')->name('official.ndrysho');
    Route::patch('/official/{id}/headship', 'OfficialController@addToHeadShip')->name('addToHeadShip');
    Route::patch('/official/{id}/headship/remove', 'OfficialController@removeFromHeadship')->name('removeFromHeadship');
    //kolegjiumet
    Route::resource('/collegium', 'CollegiumController');
    //komunat
    Route::get('/municipalities', 'MunicipalityController@index');
    //perdoruesit
    Route::resource('/user', 'UserController');

    //calendar
    Route::group(['prefix' => 'calendar/'], function () {
        Route::get('/', 'CalendarController@index');
        Route::post('/action', 'CalendarController@action');
    });

    //file-storage
    Route::group(['prefix' => 'file/'], function () {
        Route::get('/', 'FileController@index');
        Route::get('/create', 'FileController@create');
        Route::post('/store', 'FileController@store')->name('store.image');
        Route::get('/{id}/download', 'FileController@download')->name('download.image');
        Route::delete('/{id}/delete', 'FileController@destroy')->name('delete.image');
    });

    Route::get('/logout', 'Auth\LoginController@logout');
});
//Auth::routes(['register' => false]);

Auth::routes();

Route::get('/register', function (){
   return redirect('login');
});
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ config('app.locale') }}">
<head>

    <!-- Basic -->
    <meta charset="UTF-8">

    <title>@yield('page_name')</title>
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link rel="icon" href="https://komunat-ks.net/wp-content/uploads/2018/09/cropped-asociacioni_komunat1-1-32x32.jpg" sizes="32x32">

    <!-- Web Fonts  -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:100,300,400,600,800,900|Shadows+Into+Light" rel="stylesheet" type="text/css">
    <!-- Vendor CSS -->
    <link rel="stylesheet" href="{{asset('vendor/bootstrap/css/bootstrap.css')}}" />
    <link rel="stylesheet" href="{{asset('vendor/animate/animate.css')}}">

    <link rel="stylesheet" href="{{asset('vendor/font-awesome/css/all.min.css')}}" />
    <link rel="stylesheet" href="{{asset('vendor/magnific-popup/magnific-popup.css')}}" />
    <link rel="stylesheet" href="{{asset('vendor/bootstrap-datepicker/css/bootstrap-datepicker3.css')}}" />

    <!-- Specific Page Vendor CSS -->
    @yield('custom_header')
    <!--(remove-empty-lines-end)-->

    <!-- Theme CSS -->
    <link rel="stylesheet" href="{{asset('css/theme.css')}}" />

    <!--(remove-empty-lines-end)-->
    <script src="{{asset('vendor/modernizr/modernizr.js')}}"></script>


    <!-- Skin CSS -->
    <link rel="stylesheet" href="{{asset('css/skins/default.css')}}" />

    <!-- Theme Custom CSS -->
    <link rel="stylesheet" href="{{asset('css/custom.css')}}">

    <!-- Head Libs -->
</head>

<body>
<section class="body">

    <!--  Header located: layouts>header.blade.php  -->
    @include('layouts.header')

    <!--  Notifications-alerts..etc. located: layouts>notifications.blade.php  -->

    <div class="inner-wrapper">

        <!--  Sidebar located: layouts>sidebar.blade.php  -->
        @include('layouts.sidebar')

        <section role="main" class="content-body">
            <header class="page-header">
                <h2>@yield('page_name')</h2>
            </header>

        @include('layouts.notifications')
            <!-- start: page -->
        @yield('content')
        <!-- end: page -->

        </section>
    </div>

</section>
@include('layouts.footer')


<!-- Vendor -->
<script src="{{asset('vendor/jquery/jquery.js')}}"></script>
<script src="{{asset('vendor/jquery-browser-mobile/jquery.browser.mobile.js')}}"></script>
<script src="{{asset('vendor/popper/umd/popper.min.js')}}"></script>
<script src="{{asset('vendor/bootstrap/js/bootstrap.js')}}"></script>
<script src="{{asset('vendor/bootstrap-datepicker/js/bootstrap-datepicker.js')}}"></script>
<script src="{{asset('vendor/common/common.js')}}"></script>
<script src="{{asset('vendor/nanoscroller/nanoscroller.js')}}"></script>
<script src="{{asset('vendor/magnific-popup/jquery.magnific-popup.js')}}"></script>
<script src="{{asset('vendor/jquery-placeholder/jquery.placeholder.js')}}"></script>
<!-- Specific Page Vendor -->
@yield('custom_footer')
<!-- Theme Base, Components and Settings -->
<script src="{{asset('js/theme.js')}}"></script>

<!-- Theme Custom -->
<script src="{{asset('js/custom.js')}}"></script>

<!-- Theme Initialization Files -->
<script src="{{asset('js/theme.init.js')}}"></script>
<!-- Examples -->


</body>
</html>

resources/views/layouts/footer.blade.php
<div>
    <section style="background-color: #1D2127;" class="section bg-color-dark-scale-5 border-0 m-0 py-1">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="copyright bg-color-dark-scale-4 py-4">
                        <div class="container text-center py-2">
                             <p class="text-center text-muted mt-3 mb-3">&copy; {{ date('Y') }} @lang('messages.Copyright')  <a href="https://tagdigitals.com/en/" target="blank">TAG Digitals</a>  - @lang('messages.All Rights Reserved')</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

resources/views/layouts/header.blade.php
<!-- start: header -->
<header class="header">
    <div class="logo-container">
        <a href="/" class="logo">
            <img src="{{asset('img/logo.png')}}" width="204" height="44" alt="Porto Admin"/>
        </a>
        <div class="d-md-none toggle-sidebar-left" data-toggle-class="sidebar-left-opened" data-target="html"
             data-fire-event="sidebar-left-opened">
            <i class="fas fa-bars" aria-label="Toggle sidebar"></i>
        </div>
    </div>

    <!-- start: search & user box -->
    <div class="header-right">

        <span class="separator"></span>
        <?php $lang = app()->getLocale(); ?>
        <ul class="notifications">
            <li>
                <a href="#" class="dropdown-toggle notification-icon" data-toggle="dropdown" aria-expanded="false">
                    <i class="fas fa-calendar-alt"></i>
                    <span class="badge">{{$events->count()}}</span>
                </a>
                <div class="dropdown-menu notification-menu" style="">
                    <div class="notification-title">
                        <span class="float-right badge badge-default">{{$events->count()}}</span>
                        {{__('messages.Future Events')}}
                    </div>
                    <div class="content">
                        <ul>
                            @foreach($events->take(5) as $event)
                                <li>
                                    <a href="{{url('/calendar')}}" class="clearfix">
                                        <?php
                                        $orgDate = $event->start;
                                        $start = date("d-m-Y", strtotime($orgDate));?>
                                        <span class="title">{{$event->title}}</span>
                                        <span class="message">{{$start}}</span>
                                    </a>
                                    <hr>
                                </li>
                            @endforeach
                        </ul>


                        <div class="text-right">
                            @if($events->count() > 0)
                                <a href="{{url('/calendar')}}" class="view-more">{{__('messages.View All')}}</a>
                            @else
                                <a href="{{url('/calendar')}}" class="view-more">{{__('messages.Add Event')}}</a>
                            @endif
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <a href="#" class="dropdown-toggle notification-icon" data-toggle="dropdown">
                    @if($lang == 'sq')
                        <i class="h-50">SQ</i>
                    @endif
                    @if($lang == 'en')
                        <i class="h-50">EN</i>
                    @endif
                    @if($lang == 'sr')
                        <i class="h-50">SR</i>
                    @endif

                </a>

                <div class="dropdown-menu notification-menu">


                    <div class="content">
                        <ul>
                            <li>
                                <a href="/locale/sq" class="clearfix">
                                    <div class="image">
                                        <i class="h1">SQ</i>
                                    </div>
                                    <span class="title">Shqip</span>
                                    <span class="message">Albanski / Albanian</span>
                                </a>
                            </li>
                            <hr>
                            <li>
                                <a href="/locale/sr" class="clearfix">
                                    <div class="image">
                                        <i class="h1">SR</i>
                                    </div>
                                    <span class="title">Srbski</span>
                                    <span class="message">Serbian / Serbisht</span>
                                </a>
                            </li>
                            <hr>
                            <li>
                                <a href="/locale/en" class="clearfix">
                                    <div class="image">
                                        <i class="h1">EN</i>
                                    </div>
                                    <span class="title">English</span>
                                    <span class="message">Engleski / Anglisht</span>
                                </a>
                            </li>

                        </ul>


                    </div>
                </div>
            </li>
        </ul>

        <span class="separator"></span>

        <div id="userbox" class="userbox">
            <a href="#" data-toggle="dropdown" aria-expanded="false">
                <figure class="profile-picture">

                </figure>
                <div class="profile-info" data-lock-name="John Doe" data-lock-email="johndoe@okler.com">
                    <span class="name">{{auth()->user()->name}}</span>
                    <span class="role">Admin</span>
                </div>

                <i class="fa custom-caret"></i>
            </a>

            <div class="dropdown-menu" style="">
                <ul class="list-unstyled mb-2">
                    <li class="divider"></li>
                    <li>
                        <a role="menuitem" tabindex="-1" href="{{route('user.index')}}"><i
                                class="fas fa-user"></i> {{__('messages.My Profile')}}</a>
                    </li>
                    <li>
                        <a role="menuitem" tabindex="-1" href="/logout"><i
                                class="fas fa-power-off"></i>{{__('messages.Logout')}}</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</header>
<!-- end: header -->

resources/views/layouts/loginLayout.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
{{--    <script src="{{ asset('js/app.js') }}" defer></script>--}}

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/notifications.blade.php
<div class="container">
    <div class="row">
        <div class="col-md-12">
            @if (session('status'))
                <div class="alert alert-success text-center">
                    <strong>{{session('status')}}</strong>
                </div>
            @endif
            @if (session('error'))
                    <div class="alert alert-danger" role="alert">
                        <strong>{{session('error')}}</strong>
                    </div>
            @endif
            @if (session('danger'))
                <div class="alert alert-danger text-center">
                    <strong> {{session('danger')}}</strong>
                </div>
            @endif
            @if (session('info'))
                <div class="alert alert-info">
                    <strong> {{session('info')}}</strong>
                </div>
            @endif
            @if (session('alert-info'))
                <div class="alert alert-info alert-with-icon" data-notify="container">
                    <i class="material-icons" data-notify="icon">notifications</i>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <i class="material-icons">close</i>
                    </button>
                    <span data-notify="icon" class="now-ui-icons ui-1_bell-53"></span>
                    <span data-notify="message">{{session('alert-info')}}</span>
                </div>
            @endif
            @if (session('alert-success'))
                <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <i class="material-icons">close</i>
                    </button>
                    <span>
                      <b></b> {{session('alert-success')}}</span>
                </div>
            @endif
            @if (session('warning'))
                <div class="alert alert-warning text-center">
                    {{session('warning')}}
                </div>
            @endif
        <!-- MailChimp -->
            @if (session('status-MailChimp'))
                <div class="alert alert-success text-center">
                    {{session('status')}}
                </div>
            @endif
            @if (session('error-MailChimp'))
                <div class="alert alert-danger text-center">
                    {{session('error')}}
                </div>
            @endif
            @if ($errors->any())
                <div class="alert alert-danger text-center">
                        @foreach ($errors->all() as $error)
                            <strong>{{ $error }}</strong>
                        @if($errors->count() > 1)<br>
                        @endif
                        @endforeach
                </div>
            @endif
        </div>
    </div>
</div>

resources/views/layouts/sidebar.blade.php
<!-- start: sidebar -->
<aside id="sidebar-left" class="sidebar-left">

    <div class="sidebar-header">

        <div class="sidebar-toggle d-none d-md-block" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
            <i class="fas fa-bars" aria-label="Toggle sidebar"></i>
        </div>
    </div>

    <div class="nano">
        <div class="nano-content">
            <nav id="menu" class="nav-main" role="navigation">


                <ul class="nav nav-main">
                    <li class="{{ Request::is('/') ? 'nav-active' : '' }}">
                        <a class="nav-link" href="/">
                            <i class="fas fa-columns"></i>
                            <span>{{__('messages.Dashboard')}}</span>
                        </a>
                    </li>
                    <li class="{{ Request::is('municipalities') ? 'nav-active' : '' }}">
                        <a class="nav-link" href="{{url('/municipalities')}}">
                            <i class="far fa-building"></i>
                            <span>{{__('messages.Municipalities')}}</span>
                        </a>
                    </li>
                    <li class="{{ Request::is('mail') ? 'nav-active' : '' }}">
                        <a class="nav-link" href="{{url('/mail')}}">
                            <i class="fas fa-envelope" aria-hidden="true"></i>
                            <span>{{__('messages.Send Email')}}</span>
                        </a>
                    </li>
                    <li class="nav-parent {{ Request::is('collegium*') ? 'nav-expanded nav-active' : '' }}">
                        <a class="nav-link" href="#">
                            <i class="fas fa-industry" aria-hidden="true"></i>
                            <span>{{__('messages.Collegiums')}}</span>
                        </a>
                        <ul class="nav nav-children">
                            <li class="{{ Request::is('collegium') ? 'nav-active' : '' }}">
                                <a class="nav-link" href="{{route('collegium.index')}}">
                                    {{__('messages.Collegiums')}}
                                </a>
                            </li>
                            <li class="{{ Request::is('collegium/create') ? 'nav-active' : '' }}">
                                <a class="nav-link" href="{{route('collegium.create')}}">
                                    {{__('messages.Create Collegium')}}
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-parent {{ Request::is('official*') ? 'nav-expanded nav-active' : '' }}">
                        <a class="nav-link" href="#">
                            <i class="fas fa-user-tie"></i>
                            <span> {{__('messages.Officials')}}</span>
                        </a>
                        <ul class="nav nav-children">
                            <li class="{{ Request::is('official') ? 'nav-active' : '' }}">
                                <a class="nav-link" href="{{route('official.index')}}">
                                    {{__('messages.Officials')}}
                                </a>
                            </li>
                            <li class="{{ Request::is('official/create') ? 'nav-active' : '' }}">
                                <a class="nav-link" href="{{route('official.create')}}">
                                    {{__('messages.Create Official')}}
                                </a>
                            </li>
                            <li class="{{ Request::is('official/archive') ? 'nav-active' : '' }}">
                                <a class="nav-link" href="{{route('archive')}}">
                                    {{__('messages.Archive')}}
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-parent {{ Request::is('file*') ? 'nav-expanded nav-active' : '' }}">
                        <a class="nav-link" href="#">
                            <i class="fab fa-google-drive"></i>
                            <span>{{__('messages.File Storage')}}</span>
                        </a>
                        <ul class="nav nav-children">
                            <li class="{{ Request::is('file') ? 'nav-active' : '' }}">
                                <a class="nav-link" href="{{url('/file')}}">
                                    {{__('messages.File Storage')}}
                                </a>
                            </li>
                            <li class="{{ Request::is('file/create') ? 'nav-active' : '' }}">
                                <a class="nav-link" href="{{url('/file/create')}}">
                                    {{__('messages.Create File')}}
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="{{ Request::is('user/create') ? 'nav-active' : '' }}">
                        <a class="nav-link" href="{{route('user.create')}}">
                            <i class="fas fa-users"></i>
                            <span>{{__('messages.add user')}}</span>
                        </a>
                    </li>
                    <li class="{{ Request::is('calendar') ? 'nav-active' : '' }}">
                        <a class="nav-link" href="{{url('/calendar')}}">
                            <i class="fas fa-calendar-alt"></i>
                            <span>{{__('messages.Calendar')}}</span>
                        </a>
                    </li>
                </ul>
            </nav>
        <script>
            // Maintain Scroll Position
            if (typeof localStorage !== 'undefined') {
                if (localStorage.getItem('sidebar-left-position') !== null) {
                    var initialPosition = localStorage.getItem('sidebar-left-position'),
                        sidebarLeft = document.querySelector('#sidebar-left .nano-content');

                    sidebarLeft.scrollTop = initialPosition;
                }
            }
        </script>
        </div>

    </div>

</aside>
<!-- end: sidebar -->